-- 0002_seed.sql
-- Replace the hash with one generated by: npm run gen:password -- <plain_password>
INSERT INTO admins (username, password_hash)
VALUES ('admin', '$2b$12$ouXX3wlHH62ATrzITaBZdOYjYF1cuLTp2AyG4VugaVz8DrTuj7uqO')
ON CONFLICT(username) DO NOTHING;
